# Generated by Django 5.2.11 on 2026-02-25 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "patronymic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                        ],
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "patronymic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                        ],
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("specialization", models.CharField(max_length=100)),
                ("date_start_work", models.DateField()),
                ("date_end_work", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "patronymic_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[
                            ("male", "Мужской"),
                            ("female", "Женский"),
                            ("other", "Другой"),
                        ],
                        max_length=10,
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=12, unique=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Пациент",
                "verbose_name_plural": "Пациенты",
            },
        ),
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("registered_adress", models.CharField(max_length=150)),
                ("actual_adress", models.CharField(max_length=150)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "doctors",
                    models.ManyToManyField(related_name="clinics", to="main.doctor"),
                ),
            ],
            options={
                "verbose_name": "Клиника",
                "verbose_name_plural": "Клиники",
            },
        ),
        migrations.CreateModel(
            name="DoctorEducation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university", models.CharField(blank=True, max_length=100, null=True)),
                ("faculty", models.CharField(blank=True, max_length=100, null=True)),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_end", models.DateField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="main.doctor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Образование врача",
                "verbose_name_plural": "Образования врачей",
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Подтверждена"),
                            ("waited", "Ожидает"),
                            ("started", "Начата"),
                            ("completed", "Завершена"),
                        ],
                        default="waited",
                        max_length=20,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="main.clinic",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="main.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="main.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультация",
                "verbose_name_plural": "Консультации",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("doctor", "start_time"), name="unique_doctor_time"
                    )
                ],
            },
        ),
    ]
